def migrationMode = project.findProperty("pswgMigrationMode")?.toString()?.toBoolean() ?: false

loom {
	if (!migrationMode)
	{
		splitEnvironmentSourceSets()
	}

	mods {
		"pswg_gadgets" {
			sourceSet sourceSets.main
			if (!migrationMode)
			{
				sourceSet sourceSets.client
			}
		}
	}
}

if (migrationMode)
{
	sourceSets {
		main {
			java.srcDir("src/client/java")
			resources.srcDir("src/client/resources")
		}
	}
}

fabricApi {
	configureDataGeneration {
		modId = "pswg_gadgets"
		client = true
	}
}

dependencies {
	api(project(path: ":projects:pswg_core", configuration: "namedElements"))
	compileOnly(project(path: ":projects:framework"))
	annotationProcessor(project(path: ":projects:framework-generator"))
}
