loom {
	splitEnvironmentSourceSets()

	mods {
		"pswg_gadgets" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

fabricApi {
	configureDataGeneration {
		modId = "pswg_gadgets"
		client = true
	}
}

dependencies {
	api(project(":projects:pswg_core"))
	compileOnly(project(path: ":projects:framework"))
	annotationProcessor(project(path: ":projects:framework-generator"))
}
