package dev.pswg.datagen;

public enum DGBlockTag
{
	ARID_PLANT_PLACEABLE,
	FRAGMENTATION_GRENADE_DESTROY,
	DETONATES_GRENADE,
	BOUNCY,
	GAS_PASS_THROUGH,
	INFERNO_CHAR,
	INFERNO_DESTROY,
	PICKAXE_MINEABLE,
	SHEARS_MINEABLE,
	SHOVEL_MINEABLE,
	AXE_MINEABLE,
	SLIDING_DOOR,
	LEAVES,
	BUSH_PLACEABLE,
	DEAD_BUSH_SUBSTRATE,
	BLASTER_DESTROY,
	BLASTER_EXPLODE,
	BLASTER_REFLECT,
	LOGS,
	LOGS_THAT_BURN,
	SAND,
	SOFT,
	STAIRS
}
