loom {
	splitEnvironmentSourceSets()

	mods {
		"pswg_blasters" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

fabricApi {
	configureDataGeneration {
		modId = "pswg_blasters"
		client = true
	}
}

dependencies {
	api(project(path: ":projects:pswg_core", configuration: "namedElements"))
	compileOnly(project(path: ":projects:framework"))
	annotationProcessor(project(path: ":projects:framework-generator"))
}
