loom {
	splitEnvironmentSourceSets()

	mods {
		"pswg_core" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}

	accessWidenerPath = file("src/main/resources/pswg.accesswidener")
}

fabricApi {
	configureDataGeneration {
		modId = "pswg"
		client = true
	}
}

dependencies {
	compileOnly project(":projects:framework")
	annotationProcessor project(":projects:framework-generator")
}
